### ISSUE TITLE
Select module on Windows

### ISSUE THREAD

**Issue by jenkojan** [python-dugong/python-dugong#4]
Hi guys,

I tried installing your library on Windows 10 with 3 different python versions (all above 3.3). None worked, the problem being the 'select' inbuilt library, which seems to be different in Windows than it is in Linux (where the installation worked no problem).

Here is the traceback when I call `python setup.py install`:
``` Traceback (most recent call last):
  File "setup.py", line 108, in <module>
    main()
  File "setup.py", line 37, in main
    import dugong
  File "C:\Users\myName\Downloads\dugong-3.7.5.tar\dugong-3.7.5\dugong\__init__.py", line 28, in <module>
    from select import POLLIN, POLLOUT
ImportError: cannot import name 'POLLIN'
```

In Windows, I can `import select` but when I try `select.poll()` or `select.POLLIN` python returns AttributeError: Module select does not have poll/POLLIN attribute. The dugong package tries to execute `from select import POLLIN, POLLOUT` which is where the problem is.

Is dugong designed to work on Linux and doesn't offer Windows support? In that case please just add a note on README. Or is there something else the matter?

Thanks!

**Comment by vileishikov-pavel** [comment]
I have the same issue.

**Comment by qo4on** [comment]
Does anybody fixed this?
