### ISSUE TITLE
Does dugong support http pipelining over single TCP connection?

### ISSUE THREAD

**Issue by qo4on** [python-dugong/python-dugong#6]
Does `dugong` support `http pipelining`? Multiple requests ("Connection: keep-alive") over single TCP connection without waiting for answer.

**Comment by Nikratio** [comment]
I encourage you to take a look at the examples and the documentation.

**Comment by qo4on** [comment]
Thanks. I saw the [documentation](http://www.rath.org/dugong-docs/tutorial.html#pipelining-with-threads) and my question is a bit different. Does `dugong` guarantee that the order it sends the requests/packages is the same as the order a remote server receives them?

**Comment by Nikratio** [comment]
That is guaranteed by TCP, not dugong.

**Comment by qo4on** [comment]
This is true when you open a single TCP connection and then spawn one thread that sends the requests. Does your [async example](http://www.rath.org/dugong-docs/tutorial.html#pipelining-with-coroutines) work in this way?

By the way, your coroutine example does not work on Windows 10. It throws an error in line `loop.run_until_complete(recv_future)`:
```
Python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```
On Linux it works fine.

Add this line before `loop = asyncio.get_event_loop()`:
```
if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```
